version: "3"
services:
  webserver:
    image: php:7.4-apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./application:/var/www/html
    environment:
      SITE_URL: http://localhost
    networks:
      - test

networks:
  test:
    external: true
