version: "3.7" # Docker version
services: # Services we want to include
  www:
    container_name: photographystoreapp
    build: .
    ports:
      - 8090:80
      - 4043:443 # For future ssl traffic
    environment:
      SITE_URL: http://localhost
    depends_on:
      - db
  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - .db/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: store
