DROP DATABASE IF EXISTS HashDB;
CREATE DATABASE HashDB;
USE HashDB;


CREATE TABLE IF NOT EXISTS `hash` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `pass` varchar(60) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=14 ;